version: "3.3"

services:
  db:
    image: postgres_image_datacredito
    container_name: postgres_container_datacredito
    env_file:
      - database/database.env
    volumes:
      # Change to path for production
      - /tmp/docker/demo/data
    ports:
      # Change to port for production
      - 5437:5432
    expose:
      - 5437
    restart: always

  python-client:
    image: python_client_image
    container_name: python_client_container
    build: .
    expose:
      - 8091
    ports:
      - 8091:8091
    restart: always

  java-api:
    image: java_api_image
    container_name: java_api_container
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: always
    depends_on:
      - python-client
      - db
    links:
      - python-client:python_client_container
      - db:postgres_container_datacredito